name: uri
version: 0.11.4
description: >-
  Utilities for building and parsing URIs, including support for parsing
  URI templates as defined in RFC 6570.
homepage: https://github.com/google/uri.dart
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  matcher: ^0.12.9
  quiver: ^2.1.5

dev_dependencies:
  test: ^1.15.7
